package com.inv.xflux.entity;

import com.inv.data.access.emums.EmployeeStatus;
import com.inv.data.access.emums.Role;
import com.inv.xflux.entity.in.IEmployee;
import com.inv.data.access.in.IFlux;
import javafx.scene.image.Image;

/**
 * @author XDSSWAR
 */
public final class Employee implements IEmployee, IFlux {
    private long id;
    private String name;
    private String lastName;
    private String user;
    private String phone;
    private String email;
    private String address;
    private String birthDate;
    private EmployeeStatus status;
    private Role role;
    private Image picture;

    /**
     * Employee Constructor to load from Database
     * @param id autogenerated Parameter
     * @param name Employee Name
     * @param lastName Last Name
     * @param user Username
     * @param phone Phone
     * @param email Email
     * @param address Address
     * @param birthDate Date of Birth
     * @param status status
     * @param role role
     */
    public Employee(long id, String name, String lastName, String user, String phone,
                    String email, String address, String birthDate, EmployeeStatus status, Role role, Image picture) {
        this.id = id;
        this.name = name;
        this.lastName = lastName;
        this.user = user;
        this.phone = phone;
        this.email = email;
        this.address = address;
        this.birthDate = birthDate;
        this.status = status;
        this.role = role;
        this.picture=picture;
    }

    /**
     * Employee Constructor to create new Employee
     * @param name Employee Name
     * @param lastName Last Name
     * @param user Username
     * @param phone Phone
     * @param email Email
     * @param address Address
     * @param birthDate Date of Birth
     */
    public Employee(String name, String lastName, String user, String phone,
                    String email, String address, String birthDate,  Image picture) {
        this.name = name;
        this.lastName = lastName;
        this.user = user;
        this.phone = phone;
        this.email = email;
        this.address = address;
        this.birthDate = birthDate;
        this.picture=picture;
    }


    @Override
    public long getId() {
        return this.id;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public String getLastName() {
        return this.lastName;
    }

    @Override
    public String getUser() {
        return this.user;
    }

    @Override
    public String getPhone() {
        return this.phone;
    }

    @Override
    public String getEmail() {
        return this.email;
    }

    @Override
    public String getAddress() {
        return this.address;
    }

    @Override
    public String getBirthDate() {
        return this.birthDate;
    }

    @Override
    public EmployeeStatus getStatus() {
        return this.status;
    }

    @Override
    public Role getRole() {
        return this.role;
    }

    @Override
    public Image getPicture() {
        return this.picture;
    }

    @Override
    public boolean hasId() {
        return id != 0 && id > 0;
    }

    /**
     * Check if Admin
     * @return true when yes
     */
    public boolean isAdmin(){
        return role==Role.ADMIN;
    }

    /**
     * Check if Manager
     * @return true when yes
     */
    public boolean isManager(){
        return role == Role.MANAGER;
    }

    /**
     * Check if Employee
     * @return true when yes
     */
    public boolean isEmployee(){
        return role==Role.EMPLOYEE;
    }
}
